### ISSUE TITLE
Perform additional testing of VerifyBamId.

### ISSUE THREAD

**Issue by deflaux** [googlegenomics/dataflow-java#155]
to ensure the results match what we would expect.  
* Be sure to check that we normalize reference names so that 'chr1' in Platinum Genomes will match up with '1' in 1,000 Genomes.

**Comment by deflaux** [comment]
Be sure to split the monolithic tests in VerifyBamIdTest.java into multiple files.

**Comment by nitag** [comment]
Which tests should be split up?

**Comment by pgrosu** [comment]
Hi Nita (@nitag),

I think it's also this from Dion (@dionloy):

https://github.com/googlegenomics/dataflow-java/pull/154#discussion-diff-46444188

~p

**Comment by deflaux** [comment]
Hi @nitag!  I actually took care of splitting up the monolithic tests in https://github.com/googlegenomics/dataflow-java/pull/161 

You can see that there are bugs in this pipeline due to the tests that needed an `@Ignore`.

**Comment by deflaux** [comment]
fixed!
