### ISSUE TITLE
Dependent utils-java and grpc java bump in pom.xml

### ISSUE THREAD

**Issue by pgrosu** [googlegenomics/dataflow-java#205]
The dataflow-java pom.xml would most likely need to also need to be updated after this issue from utils-java and available in the Maven repository:

https://github.com/googlegenomics/utils-java/issues/98

Thanks,
~p

**Comment by pgrosu** [comment]
Thanks for the previous version bump, but grpc-java got updated again to 0.15.0:

https://github.com/googlegenomics/utils-java/issues/104

So the bumps would probably need to be performed again.

Thanks,
~p

**Comment by deflaux** [comment]
Fixed with https://github.com/googlegenomics/dataflow-java/pull/215
