### ISSUE TITLE
emit Genomics API counters to the Dataflow UI

### ISSUE THREAD

**Issue by deflaux** [googlegenomics/dataflow-java#35]
An Aggregator example can be found here: http://stackoverflow.com/questions/28119993/how-do-i-create-user-defined-counters-in-dataflow

Also look for opportunities to push the collection of these metrics further down the stack into utils-java so that the counters can be shared by both Spark and Dataflow.

Here's the current spark implementation:
https://github.com/googlegenomics/spark-examples/blob/master/src/main/scala/com/google/cloud/genomics/spark/examples/rdd/VariantsRDD.scala#L192

**Comment by deflaux** [comment]
This was fixed with 1ad45fc982e55052df90f2a5f38430569d50a591

**Comment by pgrosu** [comment]
Cool upgrade to the previous counts that used to be in utils.
