### ISSUE TITLE
add options for pageSize and maxCalls

### ISSUE THREAD

**Issue by deflaux** [googlegenomics/dataflow-java#36]
To manually set these values for [SearchVariantsRequest](https://developers.google.com/resources/api-libraries/documentation/genomics/v1beta2/java/latest/com/google/api/services/genomics/model/SearchVariantsRequest.html) to help with flow control issues client-side.

**Comment by pgrosu** [comment]
@deflaux, Wait, why close?  What's the alternative solution?

**Comment by pgrosu** [comment]
Are you referring to this? 

https://github.com/googlegenomics/dataflow-java/pull/40

**Comment by deflaux** [comment]
Yes, github auto-closed this issue when I merged the PR.  Github added the link to the commit in the messages here in this issue.

**Comment by pgrosu** [comment]
I see, ok thanks :)
