### ISSUE TITLE
what is the client_secrets.json in the get started guide.

### ISSUE THREAD

**Issue by jasonzhang2022** [googlegenomics/dataflow-java#48]
I already have cloud platform account and run sample data flow. I could not figure out what the client_secrets.json is in the get started guide.

**Comment by calbach** [comment]
Seems these instructions were lost in the upgrade to our new landing page. We will restore those ASAP; in the meantime:

- Create a Genomics enabled project via http://cloud.google.com/console/project.
- Click *APIs & auth* > *Credentials* on the left hand side.
- Click *Create new client ID*.
- On the *Content screen* page, fill out the required information and click *Save*.
- Under *Application type*, select *Installed application*.
- Under *Installed application type* select *Other*.
- Click *Create Client ID*.
- Under *Client ID for native application*, click *Download JSON*.
- Rename the downloaded file to `client_secrets.json` and copy it to the directory where you installed the Genomics tools.

**Comment by deflaux** [comment]
@jasonzhang2022 thanks for your question and sorry for the trouble!  We've restored the correct link to the instructions for client_secrets.json.
