### ISSUE TITLE
DataflowWorkarounds.registerCoder needs a way of not failing if it's called twice for the same Class

### ISSUE THREAD

**Issue by lbergelson** [googlegenomics/dataflow-java#60]
Currently if you call `registerCoder` twice to register a coder a for the same class, you get an exception.

It would be nice to delegate registration of coders to the transforms that produce data of that type.  You can't really do this now though, because two transforms that both try to register the same coder will throw an exception.  
Alternatively, how can I figure out if a coder for a class is already registered?   `CoderRegistry` offers `getDefaultCoder` methods, but I couldn't figure out how to actually call it if I just have a `Class` object.

**Comment by pgrosu** [comment]
Hi Louis,

You should be able to run `getDefaultCoder` via the following and perform a `try/catch` to ensure the Exception does not stop your program - in this case `p` is a `Pipeline`:

```
p.getCoderRegistry().getDefaultCoder( Your_Instantiated_Class );
```

More examples are available here:

https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/test/java/com/google/cloud/dataflow/sdk/coders/CoderRegistryTest.java#L169-175

Hope it helps,
Paul

**Comment by deflaux** [comment]
@lbergelson with some recent updates to the Dataflow SDK, I think all the coder registry stuff could be simplified greatly and we may be able to do away with the DataflowWorkarounds class.

See [registry.setFallbackCoderProvider](https://cloud.google.com/dataflow/java-sdk/JavaDoc/com/google/cloud/dataflow/sdk/coders/CoderRegistry#setFallbackCoderProvider(com.google.cloud.dataflow.sdk.coders.CoderProvider)) and the [code and tests](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/search?utf8=%E2%9C%93&q=setFallbackCoderProvider).

**Comment by pgrosu** [comment]
Oh cool!  How can get announcements of updates to the Dataflow SDK?  Is there a location of all the updates?

Thanks Nicole,
Paul

**Comment by wbrockman** [comment]
Paul, Release notes for the sdk are here: 
https://cloud.google.com/dataflow/release-notes/java
and release notes for the service are here: 
https://cloud.google.com/dataflow/release-notes/service

**Comment by wbrockman** [comment]
This is another area for cleanup. David @davidadamsphd or I may be able to do it in the near future; the issue tracker here seems like a reasonable place to track it in the meantime.

**Comment by pgrosu** [comment]
Thank you @wbrockman, though looking through them just now I don't see the announcement for `setFallbackCoderProvider` - but relating to this - that `getCoderRegistry()` will soon be deleted.  It would be nice to also have just a description line added for `setFallbackCoderProvider`, even though [the code](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/coders/CoderRegistry.java#L632-634) looks straightforward:

```Java
public void setFallbackCoderProvider(CoderProvider coderProvider) {
    fallbackCoderProvider = coderProvider;
  }
```

Anyway, I'm super-impressed with how many additions Dataflow is getting.  Very cool to see the concepts from the [FlumeJava](http://research.google.com/pubs/archive/35650.pdf) and [MillWheel](http://research.google.com/pubs/archive/41378.pdf) papers being implemented into the SDK.

Many thanks!
~p
