### ISSUE TITLE
Update offline credentials in GenomicsApiReader 

### ISSUE THREAD

**Issue by davidadamsphd** [googlegenomics/dataflow-java#72]
Right now GenomicsApiReader takes a GenomicsFactory.OfflineAuth (which needs to be constructed from GCSOptions). I think this can be simplified.
1) There is now secrets built into the DataflowPipelineOptions directly (get/setSecretsFile), so we don't need get/setGenomicsSecretsFile.

2) It might also be possible to simplify the code a little more since now the DataflowPipelineOptions now has get/setCredentialFactoryClass. I think this could mean fewer args passed around since ProcessContext has getPipelineOptions.

**Comment by pgrosu** [comment]
By all means, please feel free to create a pull-request.

~p

**Comment by deflaux** [comment]
@davidadamsphd Is this issue complete now?  Or is there more work to do?

**Comment by davidadamsphd** [comment]
Complete, closing.

**Comment by pgrosu** [comment]
@davidadamsphd Don't forget about the one to go through OAuth flow once :)

https://github.com/googlegenomics/dataflow-java/issues/95

~p
