### ISSUE TITLE
Add integration test for AnnotateVariants pipeline.

### ISSUE THREAD

**Issue by deflaux** [googlegenomics/dataflow-java#79]
Something similar to [CountReadsITCase.java](https://github.com/googlegenomics/dataflow-java/blob/master/src/test/java/com/google/cloud/genomics/dataflow/pipelines/CountReadsITCase.java) would be great.

**Comment by calbach** [comment]
The TextIO sink is more or less placeholder for doing something real. Feel free to swap it out with something more generic if it makes testing more sane.
